export const conferenceData = [
  {
    id: 1,
    year: 2026,
    title: "A Scoping Review of Ageing and Climate Change in Southern Africa",
    location: "Oxford, UK",
    authors: "Durosaiye, I., Sadiq, I., Tekin, M., & Lazaro, M.",
    conference: "British Society of Gerontology 55th Annual Conference",
    date: "24–26 June 2026",
    citation: "Durosaiye, I., Sadiq, I., Tekin, M., & Lazaro, M. (2026). A Scoping Review of Ageing and Climate Change in Southern Africa. British Society of Gerontology 55th Annual Conference, Oxford Brookes University, Oxford, UK.",
    pdfUrl: "#", 

  },
  {
    id: 2,
    year: 2023,
    title: "Invisible in Plain Sight? Grandfathers Caring for Orphaned Grandchildren in Rural Malawi",
    location: "Norwich, England",
    authors: "Lazaro, M., Robson, E., & Walker, L.",
    conference: "Development Studies Association (DSA) Annual Conference",
    date: "14 June – 2 July 2021",
    citation: "Lazaro, M., Robson, E., & Walker, L. (2021). Invisible in plain sight? Grandfathers caring for orphaned grandchildren in rural Malawi. Development Studies Association Annual Conference, University of East Anglia, Norwich, England.",
    pdfUrl :  "pdfs/Lazaro et al 2023 - Invisible in Plain Sight.pdf"
  },
  {
    id: 3,
    year: 2019,
    title: "Towards Capability in Ageing – From Cell to Society",
    location: "Gothenburg, Sweden",
    authors: "Lazaro, M.",
    conference: "International Association of Gerontology and Geriatrics European Region Congress",
    date: "23–25 May 2019",
    citation: "Lazaro, M. (2019). International Association of Gerontology and Geriatrics European Region Congress 2019, Gothenburg, Sweden.",
  },
  {
    id: 4,
    year: 2018,
    title: "Grandfathers Caring for Orphaned Grandchildren in Rural Southern Malawi: Invisible in Plain Sight?",
    location: "Hull, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "SES PhD Research Day",
    date: "25 January 2018",
    citation: "Lazaro, M.C. (2018). Grandfathers caring for orphaned grandchildren in rural Southern Malawi: Invisible in Plain Sight? SES PhD Research Day, University of Hull, UK.",
    pdfUrl: "pdfs/Lazaro 2018 PhD Thesis.pdf",
  }, 
  {
    id: 5,
    year: 2017,
    title: "Exploring the Emotional Cost of Researching in Communities Affected by HIV/AIDS and Poverty in Malawi",
    location: "Leeds, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "5th Annual Researchers in Development Network Conference",
    date: "27 January 2017",
    citation: "Lazaro, M.C. (2017). Exploring the emotional cost of researching in communities affected by HIV/AIDS and poverty in Malawi. University of Leeds, UK.",
  },
  {
    id: 6,
    year: 2016,
    title: "Learning with Tears? The Emotional Cost of Researching in Communities Affected by HIV/AIDS and Poverty in Rural Southern Malawi",
    location: "London, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "The Process and Challenges of Conducting Research on Africa",
    date: "3 November 2016",
    citation: "Lazaro, M.C. (2016). Learning with tears? The emotional cost of researching in communities affected by HIV/AIDS and poverty in rural Southern Malawi.",
  },
  {
    id: 7,
    year: 2015,
    title: "Grandparenting in the Context of HIV/AIDS and Poverty",
    location: "Hull, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "University of Hull PhD Symposium",
    date: "8 October 2015",
    citation: "Lazaro, M.C. (2015). Grandparenting in the Context of HIV/AIDS and Poverty: The Place of Grandfathers in Carework for Orphans and Vulnerable Children in Rural Southern Malawi.",
  },
  {
    id: 8,
    year: 2013,
    title: "Dealing with Household Correlations in Using Survey Data to Estimate Risk of Diarrhoea in Under-Five Children in Malawi",
    location: "Cape Town, South Africa",
    authors: "Kaombe, T.M., Simbeye, J., Ng'ambi, W.F., & Lazaro, M.C.",
    conference: "SAMSA 2013 Conference",
    date: "25–29 November 2013",
    citation: "Kaombe, T.M., Simbeye, J., Ng'ambi, W.F., & Lazaro, M.C. (2013). Dealing with Household Correlations in Using Survey Data to Estimate Risk of Diarrhoea in Under-Five Children in Malawi.",
  },
  {
    id: 9,
    year: 2011,
    title: "The Health Immigrant Effect: Changes of Immigrants and Refugees Health over Time",
    location: "Orlando, Florida, USA",
    authors: "Lazaro, M.C., Skrypnek, B.J., & Williams, D.",
    conference: "National Council on Family Relations 73rd Annual Conference",
    date: "16–19 November 2011",
    citation: "Lazaro, M.C., Skrypnek, B.J., & Williams, D. (2011). The Health Immigrant Effect: Changes of Immigrants and Refugees Health over Time.",
  },
];