export const conferenceData = [
  {
    id: 1,
    year: 2026,
    title: "A Scoping Review of Ageing and Climate Change in Southern Africa",
    location: "Oxford Brookes University, Oxford, UK.",
    authors: "Durosaiye, I., Sadiq, I., Tekin, M., & Lazaro, M.",
    conference: "British Society of Gerontology 55th Annual Conference, 24-26 June 2026, Oxford Brookes University, Oxford, UK.",
    date: "24–26 June 2026",
    citation: "Durosaiye, I., Sadiq, I., Tekin, M., & Lazaro, M. (2026). A Scoping Review of Ageing and Climate Change in Southern Africa. British Society of Gerontology 55th Annual Conference, 24-26 June 2026, Oxford Brookes University, Oxford, UK.",
    pdfUrl: "#", 

  },
  {
    id: 2,
    year: 2021,
    title: "Invisible in Plain Sight? Grandfathers Caring for Orphaned Grandchildren in Rural Malawi",
    location: "University of East Anglia, Norwich, England",
    authors: "Lazaro, M., Robson, E., & Walker, L.",
    conference: "Development Studies Association (DSA) 2021 Annual Conference (Virtual), “Ageing and older age: unsettling development assumptions”. University of East Anglia, Norwich, England",
    date: "14 June – 2 July 2021",
    citation: "Lazaro, M., Robson, E., & Walker, L. (2021). Invisible in plain sight? Grandfathers caring for orphaned grandchildren in rural Malawi. Development Studies Association (DSA) 2021 Annual Conference (Virtual), “Ageing and older age: unsettling development assumptions”. University of East Anglia, Norwich, England",
    pdfUrl :  "pdfs/conference/Lazaro et al 2023 - Invisible in Plain Sight.pdf"
  },
  {
    id: 3,
    year: 2019,
    title: " International Association of Gerontology and Geriatrics European Region (IAGG-ER) Congress 2019",
    location: "Gothenburg, Sweden",
    authors: "Lazaro, M.",
    conference: " International Association of Gerontology and Geriatrics European Region (IAGG-ER) Congress 2019, Gothenburg, Sweden. ‘Towards Capability in Ageing – From Cell to Society",
    date: "23–25 May 2019",
    citation: "Lazaro, M. (2019). Invisible in plain sight? Grandfathers caring for orphaned grandchildren in rural Malawi. International Association of Gerontology and Geriatrics European Region (IAGG-ER) Congress 2019, 23-25 May 2019, Gothenburg, Sweden. ‘Towards Capability in Ageing – From Cell to Society",
  },
  {
    id: 4,
    year: 2018,
    title: "Grandfathers Caring for Orphaned Grandchildren in Rural Southern Malawi: Invisible in Plain Sight?",
    location: "University of Hull, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "SES PhD Research Day, University of Hull, UK",
    date: "25 January 2018",
    citation: "Lazaro, M.C. (2018). Grandfathers caring for orphaned grandchildren in rural Southern Malawi: Invisible in Plain Sight? SES PhD Research Day – January 25, University of Hull, UK.",
    pdfUrl: "pdfs/conference/Lazaro 2018 PhD Thesis.pdf",
  }, 
  {
    id: 5,
    year: 2017,
    title: "Exploring the Emotional Cost of Researching in Communities Affected by HIV/AIDS and Poverty in Malawi",
    location: "University of Leeds, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "The 5th Annual Researchers in Development Network (RiDNet) Conference “I, Researcher: exploring the research experience - context, self and interdisciplinary practice” University of Leeds, United Kingdom",
    date: "27 January 2017",
    citation: "Lazaro, M.C. (2017). Exploring the emotional cost of researching in communities affected by HIV/AIDS and poverty in Malawi. The 5th Annual Researchers in Development Network (RiDNet) Conference “I, Researcher: exploring the research experience - context, self and interdisciplinary practice” – January 27, University of Leeds, United Kingdom",
  },
  {
    id: 6,
    year: 2016,
    title: "Learning with Tears? The Emotional Cost of Researching in Communities Affected by HIV/AIDS and Poverty in Rural Southern Malawi",
    location: "University of London, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "The Process and Challenges of Conducting Research on Africa: From the Library to the Field, Royal Holloway, University of London, United Kingdom",
    date: "3 November 2016",
    citation: "Lazaro, M.C. (2016). Learning with tears? The emotional cost of researching in communities affected by HIV/AIDS and poverty in rural Southern Malawi. The Process and Challenges of Conducting Research on Africa: From the Library to the Field – November 3, Royal Holloway, University of London, United Kingdom",
  },
  {
    id: 7,
    year: 2015,
    title: "Grandparenting in the Context of HIV/AIDS and Poverty",
    location: "University of Hull, United Kingdom",
    authors: "Lazaro, M.C.",
    conference: "PhD Symposium “Lightning Talk” University House (Students’ Union Building), University of Hull, Hull, United Kingdom",
    date: "8 October 2015",
    citation: "Lazaro, M.C. (2015). Grandparenting in the Context of HIV/AIDS and Poverty: The Place of Grandfathers in Carework for Orphans and Vulnerable Children in Rural Southern Malawi. PhD Symposium “Lightning Talk” — October 8, University House (Students’ Union Building), University of Hull, Hull, United Kingdom",
  },
  {
    id: 8,
    year: 2013,
    title: "Dealing with Household Correlations in Using Survey Data to Estimate Risk of Diarrhoea in Under-Five Children in Malawi",
    location: "Cape Town, South Africa",
    authors: "Kaombe, T.M., Simbeye, J., Ng'ambi, W.F., & Lazaro, M.C.",
    conference: "SAMSA 2013 Conference, Cape Town, South Africa",
    date: "25–29 November 2013",
    citation: "Kaombe, T.M., Simbeye, J., Ng’ambi, W.F., & Lazaro, M.C. (2013). Dealing with Household Correlations in using Survey Data to estimate Risk of Diarrhoea in Under-Five Children in Malawi. SAMSA 2013 Conference, 25-29 November, Cape Town, South Africa",
  },
  {
    id: 9,
    year: 2011,
    title: "The Health Immigrant Effect: Changes of Immigrants and Refugees Health over Time",
    location: "Orlando, Florida, USA",
    authors: "Lazaro, M.C., Skrypnek, B.J., & Williams, D.",
    conference: "The National Council for Family Relations 73rd Annual Conference “Families and the Shifting Economy” – Rosen Center Hotel, Orlando, Florida, US.",
    date: "16–19 November 2011",
    citation: " Lazaro, M.C., Skrypnek, B.J., & Williams, D. (2011). The Health Immigrant Effect: Changes of Immigrants and Refugees Health over Time. The National Council for Family Relations 73rd Annual Conference “Families and the Shifting Economy” – November 16-19, 2011, Rosen Center Hotel, Orlando, Florida, US.",
  },
];